### ISSUE TITLE
Internal shaders broken

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-ppsspp#36]
Can anyone confirm if the baked in PPSSPP shaders are still working? not working in win x64

**Comment by RagnaStrife** [comment]
Not working at all.

**Comment by bleakassassin** [comment]
I can also confirm that PPSSPP's shaders don't work.

**Comment by twinaphex** [comment]
They are not 'baked in', you need to put them into a specific directory in the system directory's PPSSPP folder.

**Comment by bleakassassin** [comment]
Placing the PPSSPP in either of the implied directories (:/Retroarch/system/PPSSPP/assets/shaders or :/Retroarch/system/PPSSPP/shaders) does nothing.

**Comment by fr500** [comment]
Maybe they were renamed or something and we haven't updated the names in the core options

**Comment by fr500** [comment]
Not broken, it seems the folder layout has changed, move the shaders to PPSSPP/shaders and they work fine
