### ISSUE TITLE
linux mingw-w64 build fails

### ISSUE THREAD

**Issue by turkeychicken** [libretro/libretro-ppsspp#52]
gcc 4.9.2

../Core/Debugger/SymbolMap.o:SymbolMap.cpp:(.text+0x1af9): undefined reference to `mw_strcasecmp'
../Core/Debugger/SymbolMap.o:SymbolMap.cpp:(.text+0x467a): undefined reference to `mw_strcasecmp'
../Core/Debugger/SymbolMap.o:SymbolMap.cpp:(.text+0x46e9): undefined reference to `mw_strcasecmp'
../Core/Debugger/SymbolMap.o:SymbolMap.cpp:(.text+0x46fc): undefined reference to `mw_strcasecmp'
../Core/Debugger/SymbolMap.o:SymbolMap.cpp:(.text+0x4768): undefined reference to `mw_strcasecmp'
../Core/HLE/proAdhoc.o:proAdhoc.cpp:(.text+0x2b39): more undefined references to `mw_strcasecmp' follow
collect2: error: ld returned 1 exit status
Makefile:315: recipe for target 'ppsspp_libretro.dll' failed
make: *** [ppsspp_libretro.dll] Error 1

**Comment by leiradel** [comment]
How are you building it?

**Comment by turkeychicken** [comment]
make CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ platform=win

**Comment by leiradel** [comment]
in which directory are you issuing make?

**Comment by turkeychicken** [comment]
the libretro directory

**Comment by leiradel** [comment]
What does `git rev-parse HEAD` say?

**Comment by turkeychicken** [comment]
eb12e0677698e373403c31e7f6ada220851142e1

**Comment by leiradel** [comment]
I think the native submodule is pointing to the original ppsspp-native repository, and it should point to the libretro's fork.

Please clone https://github.com/libretro/ppsspp-native, copy its contents into an empty `native` subdirectory in libretro-ppsspp, and try to build it again.

**Comment by turkeychicken** [comment]
it built correctly this time

**Comment by leiradel** [comment]
Cool, I'll see with the libretro guys to make sure that the correct native submodule is initialized.

On another subject, the MinGW build is much slower than the MSVC build on some comparisons, so maybe you should try the later.
